"""empty message

Revision ID: 039047eebda8
Revises: 35f0ae8c31c4
Create Date: 2018-11-06 09:48:04.619463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '039047eebda8'
down_revision = '35f0ae8c31c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
